apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-flower
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{ .Chart.Name }}"
    component: flower
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 5555
    protocol: TCP
  selector:
    release: "{{ .Release.Name }}"
    app: "{{ .Chart.Name }}"
    component: flower
