apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{ .Chart.Name }}"
type: Opaque
data:
  fernet-key: {{ required "fernetKey must be generated" .Values.fernetKey | b64enc | quote }}
