apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{ .Chart.Name }}"
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        app: "{{ .Chart.Name }}"
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}:{{ .Values.worker.imageTag }}"
          imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
          args: [ "worker" ]
          env:
{{ include "airflow_env" . | indent 10 }}
          resources: {}
