apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-console
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ template "fullname" . }}
    component: console
