apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11300
      targetPort: 11300
      protocol: TCP
  selector:
    app: {{ template "fullname" . }}
    component: beanstalkd
