dependencies:
  - name: postgresql
    version: 0.6.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 0.5.3
    repository: https://kubernetes-charts.storage.googleapis.com/
