dependencies:
  - name: postgresql
    version: 0.6.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 0.4.2
    repository: https://kubernetes-charts.storage.googleapis.com/
